name: openbci-fmaps
channels:
- defaults
- menpo
dependencies:
- python=3.6
- pip
- mkl
- numpy
- pyserial
- xmltodict
- requests
- scipy
- matplotlib
- numba
- pyqt>=5.9
- pandas>=0.18
- opencv3
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- pytest
- pytest-cov
- pytest-mock
- pytest-timeout
- tensorflow-gpu
- joblib
- psutil
- flake8
- spyder
- numexpr
- traits>=4.6.0
- pyface>=6
- traitsui>=6

# scikit-cuda dependencies
- mako>=1.1.0

- pip:
  - appdirs
  - mne
  - https://api.github.com/repos/numpy/numpydoc/zipball/master
  - vtk
  - pyOpenBCI
  - pyvista>=0.23.0
  - mayavi
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - collections-extended
  - pytest-faulthandler
  - pytest-sugar
  - pydocstyle
  - codespell
  - python-picard
  - bitstring
  - bluepy
  - pynput
  - pylsl

  # scikit-cuda and dependencies
  - scikit-cuda>=0.5.2
  - pycuda>=2017.1
